# Generated by Django 3.1.7 on 2021-04-12 12:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_write'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='write',
            name='body',
        ),
        migrations.AddField(
            model_name='write',
            name='context',
            field=ckeditor.fields.RichTextField(default='', verbose_name='內容'),
        ),
        migrations.AddField(
            model_name='write',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='標題'),
        ),
    ]
