# Generated by Django 3.1.7 on 2021-04-12 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20210412_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='write',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 4, 12, 20, 51, 15, 464550)),
            preserve_default=False,
        ),
    ]
