# Generated by Django 3.1.7 on 2021-05-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_auto_20210427_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('男性', '男性'), ('女性', '女性'), ('其他', '其他'), ('Not To Say', '不公開')], default='男性', max_length=10, verbose_name='性別'),
            preserve_default=False,
        ),
    ]
