# Generated by Django 3.1.7 on 2021-05-11 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='None', upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('男性', '男性'), ('女性', '女性'), ('其他', '其他'), ('Not To Say', '不公開')], default='不公開', max_length=10, verbose_name='性別'),
        ),
    ]
