# Generated by Django 3.1.7 on 2021-05-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_auto_20210511_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='None', upload_to='image/', verbose_name='照片'),
        ),
    ]
