# Generated by Django 3.1.7 on 2021-05-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_auto_20210511_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('男性', '男性'), ('女性', '女性'), ('其他', '其他'), ('不公開', '不公開')], default='不公開', max_length=10, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/static/origin head.png', upload_to='%Y/%m/%d/', verbose_name='照片'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='無', max_length=20, verbose_name='暱稱'),
        ),
    ]
