# Generated by Django 3.1.7 on 2021-05-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0011_auto_20210517_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='intro',
            field=models.CharField(default='這個人很懶，什麼也沒打', max_length=100, verbose_name='自我介紹'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.png', upload_to='%Y/%m/%d/', verbose_name='照片'),
        ),
    ]
